// define a variable to import the <Verifier> or <renamedVerifier> solidity contract generated by Zokrates
var verifier = artifacts.require('verifier');

// Test verification with correct proof
// - use the contents from proof.json generated from zokrates steps
var json = require('./proof.json');

contract('verifier', accounts => {

  describe('Zok verifier', () => {

    beforeEach(async () => {
      this.contract = await verifier.new({from: accounts[0]});
    });

    it('Test verification with correct proof', async () => {

      let result = await this.contract.verifyTx.call(json.proof.a, json.proof.b, json.proof.c, json.inputs);
      assert.equal(result, true);
    });

    it('Test verification with incorrect proof', async () => {
      let input = [110888]
      let result = await this.contract.verifyTx.call(json.proof.a, json.proof.b, json.proof.c, input);
      assert.equal(result, false);
    });
    
  });
})

    
